// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt0Sq5t7RqXY3rD1G_Tvvk1gMZjwK0xa8',
    appId: '1:622827221535:web:9d29d852ff00fbeb25db2a',
    messagingSenderId: '622827221535',
    projectId: 'flutter-pong-d6002',
    authDomain: 'flutter-pong-d6002.firebaseapp.com',
    storageBucket: 'flutter-pong-d6002.firebasestorage.app',
    measurementId: 'G-GN7Z7WL8CV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoPIdeGp1q6eLhPD8_puU_069qUmxx4rQ',
    appId: '1:622827221535:android:f7e00ebf1288298425db2a',
    messagingSenderId: '622827221535',
    projectId: 'flutter-pong-d6002',
    storageBucket: 'flutter-pong-d6002.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPwwslLlEHP3ei93LgrviLbGkOThw0yi8',
    appId: '1:622827221535:ios:f2a1c3f29341d1da25db2a',
    messagingSenderId: '622827221535',
    projectId: 'flutter-pong-d6002',
    storageBucket: 'flutter-pong-d6002.firebasestorage.app',
    iosBundleId: 'com.dulutan.pong',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPwwslLlEHP3ei93LgrviLbGkOThw0yi8',
    appId: '1:622827221535:ios:f2a1c3f29341d1da25db2a',
    messagingSenderId: '622827221535',
    projectId: 'flutter-pong-d6002',
    storageBucket: 'flutter-pong-d6002.firebasestorage.app',
    iosBundleId: 'com.dulutan.pong',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt0Sq5t7RqXY3rD1G_Tvvk1gMZjwK0xa8',
    appId: '1:622827221535:web:c413b51267892ead25db2a',
    messagingSenderId: '622827221535',
    projectId: 'flutter-pong-d6002',
    authDomain: 'flutter-pong-d6002.firebaseapp.com',
    storageBucket: 'flutter-pong-d6002.firebasestorage.app',
    measurementId: 'G-0TSMH2BTCN',
  );
}
